### ISSUE TITLE
Maven build Errors

### ISSUE THREAD

**Issue by wilsalv** [kzr-soze/Traffic_Integration#1] opened 2018-02-28 20:23 UTC
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.096 s
[INFO] Finished at: 2018-02-28T13:52:42-06:00
[INFO] Final Memory: 11M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Traffic_Integration: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by jmwolff3** [comment] 2018-02-28 20:55
On a non windows system, the issue is caused by the line
`<executable>C:\Program Files\Java\jdk-9.0.4\bin\javac</executable>`
in the pom.xml file. It doesn't appear to be necessary on my system to build.

**Comment by jmwolff3** [comment] 2018-02-28 22:18
That being said, I am having a problem running the jar after building it, regardless of weather the javac binary is included. I get the error:
`no main manifest attribute, in target/Traffic_Integration-1.0-SNAPSHOT.jar`

Steps to reproduce:
` mvn clean install && mvn compile`
`java -jar target/Traffic_Integration-1.0-SNAPSHOT.jar Mapquest`

**Comment by kzr-soze** [comment] 2018-03-12 18:33
Fixed by jmwolff3

**Closed as completed by kzr-soze** 2018-03-12 18:33 UTC
